spring:
  web:
    locale: ko_KR
    locale-resolver: fixed
  jpa:
    properties:
        default_batch_fetch_size: 10
    database-platform: org.hibernate.dialect.MySQLDialect

openai:
  model: gpt-3.5-turbo

schedule:
  delay:
    match-picture-generate-schedule: 600000

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /springdoc/swagger-ui.html
    url: /springdoc/api-docs
  api-docs:
    path: /springdoc/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  cache:
    disabled: true
  show-login-endpoint: true
  paths-to-match:
    - /api/**
    - /
  packages-to-scan: com.gt.genti




